version: '3'

services:

  api:
    build: ./backend
    container_name: api
    ports:
      - 8000:8000
    
  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - 3000:3000

      


